main/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', start_login, name='login_page'),
    #path('', site_stop),
    path('user_home/', user_home, name='user_home'),
    path('logout/', userlogout, name='user_logout'),
    path('staff_home/', staff_home, name='staff_home'),
    path('load_data/<str:mod_name>/', admin_load_data, name='admin_load_data_page'),
    path('logs_list/', LogsList.as_view(), name='logs_page'),
    path('help/', HelpPage.as_view(), name='help_page'),
]

reports/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('report-export/<int:report_pk>', export_report_xls, name='report_export'),
    path('reports-list/', ReportsForStaff.as_view(), name='reports_list'),
    path('report-change-status/', ReportChangeStatus, name='report-change-status'),
    path('record-remarks/', RecordRemarks, name='record-remarks'),
    path('record-verified/', RecordVerified, name='record-verified'),
    path('report-add/', ReportAdd, name='report-add'),
    path('report-update/<int:report_pk>', ReportUpdate, name='report-update'),
    path('report-send/', ReportSend, name='report-send'),
    path('report-change-status/', ReportChangeStatus, name='report-change-status'),
    path('report-save-document/', ReportDocumet, name='report-save-document'),
    path('report/<int:pk>', ReportDetail.as_view(), name='report_page'),
    path('report-delete/<int:report_pk>', ReportDelete, name='report_delete'),
    path('record-add/<int:report_pk>', RecordAdd.as_view(), name='record_add_page'),
    path('record-update/<int:pk>', RecordUpdate.as_view(), name='record_update_page'),
    path('ajax/codes-load/', load_codes_data, name='ajax_load_codes'),
    path('ajax/models-load/', load_models_data, name='ajax_load_models'),
    path('ajax/work-price-load/', load_work_price_data, name='ajax_load_work-price'),
    path('record-delete/<int:report_pk>', RecordDelete, name='record_delete'),
]

reportssite/urls.py
from functools import partial
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import server_error, page_not_found, permission_denied


handler403 = partial(permission_denied, template_name='errs/403.html')
handler404 = partial(page_not_found, template_name='errs/404.html')
handler500 = partial(server_error, template_name='errs/500.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('centres/', include('servicecentres.urls')),
    path('products/', include('products.urls')),
    path('reports/', include('reports.urls')),
    path('import/', include('importData.urls'))
]

reports/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, Q
from django.urls import reverse
from main.my_validators import ChangeloggableMixin
from servicecentres.models import ServiceCenters
from main.business_logic import REPORT_STATUS, STATUS_DRAFT, WORKTYPE, FACTORIES, MONTH_CHOICES
from products.models import Codes, MainProducts, Models
from django.db.models.signals import pre_save, post_save, pre_delete
from django.dispatch import receiver


def ReportDateValidation(self):
    return Reports.ojects.filter(report_date=self.report_date).exclude(pk=self.pk)


class Reports(ChangeloggableMixin, models.Model):
    service_center = models.ForeignKey(ServiceCenters, on_delete=models.CASCADE, verbose_name='Сервисный центр')
    report_date = models.DateField(verbose_name='Отчетный период')
    note = models.TextField(blank=True, null=True, verbose_name='Примечание')
    invoice = models.CharField(max_length=250, blank=True, null=True, verbose_name='Реквизиты счета')
    act = models.CharField(max_length=250, blank=True, null=True, verbose_name='Реквизиты акта')
    mail_date = models.DateField(blank=True, null=True, verbose_name='Дата приема корреспонденции')
    user = models.ForeignKey(User, verbose_name=u'Автор отчета', on_delete=models.PROTECT, limit_choices_to={'is_staff': False})
    status = models.CharField(choices=REPORT_STATUS, max_length=100, verbose_name='Статус', default=STATUS_DRAFT)
    total_cost = models.FloatField(default=0, verbose_name='Общая сумма по отчету')
    total_work = models.FloatField(default=0, verbose_name='Общая сумма за работы')
    total_part = models.FloatField(default=0, verbose_name='Общая сумма за детали')
    total_move = models.FloatField(default=0, verbose_name='Общая сумма за выезд')
    records_count = models.IntegerField(default=0, verbose_name='Количестов ремонтов')
    verified_count = models.IntegerField(default=0, verbose_name='Количестов принятых ремонтов')
    have_fault = models.BooleanField(default=False, blank=True, verbose_name='Имеет ошибки')
    pay_date = models.DateField(blank=True, null=True, verbose_name='Дата передачи в оплату')

    class Meta():
        verbose_name = 'Отчет'
        verbose_name_plural = 'Отчеты'
        ordering = ['-report_date', 'service_center', 'status']

    def __str__(self):
        date = self.report_date
        return self.service_center.title + ' за ' + date.strftime("%B %Y")

    def get_report_month(self):
        return ' '.join([MONTH_CHOICES[self.report_date.month-1][1], self.report_date.strftime("%Y")])

    def get_absolute_url(self):
        return reverse('report_page', kwargs={"pk": self.pk, })


class ReportsRecords(ChangeloggableMixin, models.Model):
    product = models.ForeignKey(MainProducts, verbose_name='Тип продукции', on_delete=models.PROTECT)
    model = models.ForeignKey(Models, null=True, blank=True, verbose_name='Модель продукции', on_delete=models.PROTECT)
    work_type = models.CharField(choices=WORKTYPE, max_length=50, verbose_name='Вид ремонта')
    client = models.CharField(max_length=150, null=True, blank=True, verbose_name='Клиент')
    client_phone = models.CharField(max_length=150, null=True, blank=True, verbose_name='Телефон клиента')
    client_addr = models.CharField(max_length=250, null=True, blank=True, verbose_name='Адрес клиента')
    model_description = models.CharField(max_length=150, verbose_name='Модель продукции', blank=True)
    serial_number = models.CharField(max_length=30, verbose_name='Серийный номер')
    buy_date = models.DateField(null=True, blank=True, verbose_name='Дата покупки')
    start_date = models.DateField(verbose_name='Дата начала ремонта')
    end_date = models.DateField(verbose_name='Дата окончания ремонта')
    work_cost = models.FloatField(default=0, verbose_name='За работу')
    move_cost = models.FloatField(default=0, verbose_name='За выезд', blank=True)
    problem_description = models.TextField(verbose_name='Описание проблемы')
    work_description = models.TextField(verbose_name='Описание работ', blank=True)
    code = models.ForeignKey(Codes, verbose_name='Код неисправности', on_delete=models.PROTECT, limit_choices_to={'is_folder': False})
    note = models.CharField(max_length=250, verbose_name='Примечание', blank=True)
    report = models.ForeignKey(Reports, verbose_name='Отчет', on_delete=models.CASCADE, blank=True, null=True)
    parts_cost = models.FloatField(default=0, verbose_name='За детали', blank=True)
    total_cost = models.FloatField(default=0, verbose_name='Всего за ремонт', blank=True)

    verified = models.BooleanField(default=False, verbose_name='Принят')
    factory = models.CharField(choices=FACTORIES, null=True, max_length=1, verbose_name='Завод-изготовитель', blank=True)
    main_date = models.DateField(null=True, verbose_name='Дата производства', blank=True)
    shift = models.CharField(null=True, max_length=1, verbose_name='Рабочая смена', blank=True)
    errors = models.TextField(verbose_name='Ошибки', null=True, blank=True)
    remarks = models.TextField(verbose_name='Замечания', null=True, blank=True)
    have_general_errors = models.BooleanField(default=False, verbose_name='Требует внимания старшего менеджера')
    verified_date = models.DateField(verbose_name='Дата приема записи', null=True, blank=True)

    class Meta():
        verbose_name = 'Ремонт'
        verbose_name_plural = 'Ремонты'
        ordering = ['report', ]

    def get_absolute_url(self):
        return reverse('record_update_page', kwargs={"pk": self.pk, })


class ReportsParts(ChangeloggableMixin, models.Model):
    title = models.CharField(max_length=250, verbose_name='Наименование')
    price = models.IntegerField(null=True, blank=True, verbose_name='Цена')
    count = models.IntegerField(null=True, verbose_name='Количество')
    document = models.CharField(max_length=250, verbose_name='Реквизиты накладной')
    record = models.ForeignKey(ReportsRecords, verbose_name='Отчет', on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'Деталь из ремонта'
        verbose_name_plural = 'Детали из ремонта'
        ordering = ['record', 'title']

    def __str__(self):
        return self.title


@receiver(pre_save, sender=Reports)
def report_pre_save(sender, instance, **kwargs):
    qset = instance.reportsrecords_set.all()
    if qset:
        instance.records_count = qset.count()
        result = qset.aggregate(total_sum=Sum('total_cost'))
        instance.total_cost = result['total_sum']
        result = qset.aggregate(parts_sum=Sum('parts_cost'))
        instance.total_part = result['parts_sum']
        result = qset.aggregate(work_sum=Sum('work_cost'))
        instance.total_work = result['work_sum']
        result = qset.aggregate(move_sum=Sum('move_cost'))
        instance.total_move = result['move_sum']
        if qset.filter(~Q(errors=None)):
            instance.have_fault = True
        else:
            instance.have_fault = False
        instance.verified_count = qset.filter(verified=True).count()
        if instance.verified_count == instance.records_count and instance.status == 'received':
            instance.status = 'verified'


@receiver(post_save, sender=ReportsRecords)
def record_post_save(sender, instance, **kwargs):
    instance.report.save()


@receiver(pre_delete, sender=ReportsRecords)
def record_pre_delete(sender, instance, **kwargs):
    instance.product = None
    instance.model = None

reports/templates/reports/codes_list_get.html
<option>---------</option>
{% for group in groups %}
<optgroup label="{{ group }}">
    {% for code in codes %}
    {% if code.parent.pk == group.pk %}
        {% if code.pk == select_id %}
        <option selected value="{{ code.pk }}">{{ code }}</option>
        {% else %}
        <option value="{{ code.pk }}">{{ code }}</option>
        {% endif %}
    {% endif %}
    {% endfor %}
{% endfor %}

reports/templates/reports/models_list_get.html
<option>---------</option>
{% for group in groups %}
<option value="{{ group.pk }}">{{ group }}</option>
{% endfor %}

reports/templates/reports/price_get.html
{{ price }}

reports/templates/reports/report_page.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}{{ report.report_date|date:"F Y"|lower }}
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% if request.user.is_staff %}
    {% include 'inc/staff_navbar.html' %}
{% else %}
    {% include 'inc/user_navbar.html' %}
{% endif %}

<div class="container">
    <!-- ЗАГОЛОВОК ОТЧЕТА !-->
    <div class="row pt-2">
        {% if request.user.is_staff %}
            {% show_report_header_for_staff report False %}
        {% else %}
            {% show_report_header report True rep_form %}
        {% endif %}
    </div>
    <!-- ЗАПИСИ !-->
    <div class="row">
        {% for record in records %}
        <div class="card mt-1" id="record-{{ record.pk }}">
            <div class="card-body">
                <div class="row p-2 mb-2 bg-light text-dark border align-items-center">
                    <div class="col-xl-2">
                        {% if request.user.is_staff or report.status == 'refinement' %}
                            {% if record.verified %}
                            <i class="bi bi-check-square-fill text-success"></i>
                            {% else %}
                            <i class="bi bi-square text-danger"></i>
                            {% endif %}
                        {% endif %}
                        <strong class="m-2">{{ record.get_work_type_display }}</strong>
                    </div>
                    <div class="col-xl-4"><strong>{{ record.product }}</strong></div>
                    <div class="col-xl-3"><strong>{{ record.model_description }}</strong></div>
                    <div class="col-xl-2"><strong>{{ record.serial_number }}</strong></div>
                    <div class="col-xl-1 text-end">
                        {% if request.user.is_staff and not request.user.is_superuser %}
                            <a href="{% url 'record_update_page' record.pk %}" class="btn btn-outline-primary btn-sm"><i class="bi bi-eye"></i></a>
                        {% else %}
                            {% if report.status == 'draft' or report.status == 'refinement' %}
                                {% if record.verified %}
                                <a href="{% url 'record_update_page' record.pk %}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-eye"></i></a>
                                {% else %}
                                <a href="{% url 'record_update_page' record.pk %}"class="btn btn-outline-primary btn-sm"><i class="bi bi-pencil"></i></a>
                                {% endif %}
                            {% else %}
                            <a href="{% url 'record_update_page' record.pk %}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-eye"></i></a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="row mb-1">
                    <div class="col-xl-8">
                        <div class="row">
                            {% if record.client %}
                            <div class="col-xl-4">{{ record.client }} ({{ record.client_phone }})</div>
                            {% endif %}
                            <div class="col-xl-8">
                                <div class="col-xl-12"><label class="text-muted">Неисправность:</label> {{ record.problem_description|truncatewords:8 }}</div>
                                <div class="col-xl-12"><label class="text-muted">Код:</label> {{ record.code|truncatewords:8 }}</div>
                                <div class="col-xl-12"><label class="text-muted">Работы:</label> {{ record.work_description|truncatewords:8 }}</div>
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-xl-3">За работы: {{ record.work_cost }}</div>
                            <div class="col-xl-3">За выезд: {{ record.move_cost }}</div>
                            <div class="col-xl-3">За детали: {{ record.parts_cost }}</div>
                            <div class="col-xl-3"><strong>Итого: {{ record.total_cost }}</strong></div>
                        </div>
                        {% if record.note %}
                        <div class="row mt-2">
                            <div class="col-12">
                                <i class="bi bi-info-square"></i><label class="px-3">{{ record.note }}</label>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-xl-4">
                        {% show_record_parts_list record %}
                    </div>
                </div>
                {% if record.errors %}
                <div class="row mt-2">
                    <div class="col-12">
                        <i class="bi bi-exclamation-square-fill text-warning"></i></i><strong class="px-3">{{ record.errors }}</strong>
                    </div>
                </div>
                {% endif %}
                {% if record.remarks %}
                    {% if request.user.is_staff %}
                    <div class="row mt-1">
                        <div class="col-12">
                            <i class="bi bi-exclamation-square-fill text-danger"></i><strong class="px-3 text-danger">{{ record.remarks }}</strong>
                        </div>
                    </div>
                    {% elif report.status == 'refinement' %}
                    <div class="row mt-1">
                        <div class="col-12">
                            <i class="bi bi-exclamation-square-fill text-danger"></i><strong class="px-3 text-danger">{{ record.remarks }}</strong>
                        </div>
                    </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    {% if records %}
    <!-- кнопка ВВЕРХ -->
    {% include 'inc/go_to_top_button.html' %}
    {% endif %}
</div>


{% include 'inc/footer.html' %}
{% endblock %}

reports/templates/reports/reports_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for itm in reports %}
    {{ itm }}
    {% endfor %}
</body>
</html>

reports/templates/reports/staff_reports_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|Главная
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% include 'inc/staff_navbar.html' %}

<div class="container">
    <main>
        <div class="row py-4">
            <div class="col-12"><h3>{{ title }}</h3></div>
        </div>

        <div class="row g-5">
            <div class="col-lg-4  order-lg-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Найдено отчетов</span>
                    <span class="badge bg-primary rounded-pill">{{ obj_count }}</span>
                </h4>
                <form class="card p-2" method="get">
                    {% if request.user.is_superuser or request.user|has_group:"GeneralStaff" %}
                    <div class="row mb-3  align-items-center">
                        <label class="col-xl-4 col-form-label">Сервис</label>
                        <div class="col-xl-8">
                            {{ form.service_center }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="row mb-3  align-items-center">
                        <label class="col-xl-4 col-form-label">Отч. период</label>
                        <div class="col-xl-1">
                            {{ form.use_date }}
                        </div>
                        <div class="col-xl-4">
                            {{ form.month }}
                        </div>
                        <div class="col-xl-3  align-items-center">
                            {{ form.year }}
                        </div>
                    </div>
                    <div class="row mb-3  align-items-center">
                        <label class="col-xl-4">Статус</label>
                        <div class="col-xl-1">
                            {{ form.use_status }}
                        </div>
                        <div class="col-xl-7">
                            {{ form.status }}
                        </div>
                    </div>
                    {% if request.user.is_superuser or request.user|has_group:"GeneralStaff" %}
                    <div class="row mb-3  align-items-center">
                        <label class="col-xl-4">Менеджер</label>
                        <div class="col-xl-8">
                            {{ form.staff_user }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="container d-flex justify-content-center gap-2">
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="bi bi-search"></i>
                            выбрать
                        </button>
                        <a class="btn btn-outline-primary" href="{% url 'reports_list' %}" role="button">
                            <i class="bi bi-x-lg"></i>
                            сбросить
                        </a>
                    </div>
                </form>
            </div>
            <div class="col-lg-8">
                {% if reports %}
                {% for report in reports %}
                    {% if report.status == 'send' %}
                    {% show_report_header_for_staff report False %}
                    {% else %}
                    {% show_report_header_for_staff report True %}
                    {% endif %}
                {% endfor %}
                {% else %}
                <h4 class="text-center text-muted">Ничего не найдено ...</h4>
                {% endif %}
            </div>
        </div>
        {% if reports %}
        <!-- кнопка ВВЕРХ --!>
        {% include 'inc/go_to_top_button.html' %}
        {% endif %}
    </main>
    {% include 'inc/list_paginator.html' %}
</div>

{% include 'inc/footer.html' %}
{% endblock %}