main/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', start_login, name='login_page'),
    #path('', site_stop),
    path('user_home/', user_home, name='user_home'),
    path('logout/', userlogout, name='user_logout'),
    path('staff_home/', staff_home, name='staff_home'),
    path('load_data/<str:mod_name>/', admin_load_data, name='admin_load_data_page'),
    path('logs_list/', LogsList.as_view(), name='logs_page'),
    path('help/', HelpPage.as_view(), name='help_page'),
]

reportssite/urls.py
from functools import partial
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import server_error, page_not_found, permission_denied


handler403 = partial(permission_denied, template_name='errs/403.html')
handler404 = partial(page_not_found, template_name='errs/404.html')
handler500 = partial(server_error, template_name='errs/500.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('centres/', include('servicecentres.urls')),
    path('products/', include('products.urls')),
    path('reports/', include('reports.urls')),
    path('import/', include('importData.urls'))
]

main/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.db import models


def get_name(self):
    result = None
    if self:
        if self.last_name or self.first_name:
            if self.last_name:
                if self.first_name:
                    result = self.last_name+' '+self.first_name[0]
                else:
                    result = self.last_name
            else:
                result = self.first_name
        else:
            result = self.username
        return result
    return result


def get_service_center(self):
    from servicecentres.models import ServiceCenters
    try:
        center = ServiceCenters.objects.get(user=self, is_active=True)
        return center
    except Exception:
        return None



User.add_to_class("__str__", get_name)

User.add_to_class("service_center", get_service_center)



# модель для записи действий пользователей
# взято отсюда: https://webdevblog.ru/logirovanie-izmeneniya-dannyh-v-modelyah-django/

ACTION_CREATE = 'create'
ACTION_UPDATE = 'update'
ACTION_DELETE = 'delete'

MODEL_CODES = 'Codes'
MODEl_PRODUCT = 'MainProducts'
MODEL_PODUCT_MODELS = 'Models'
MODE_BASE_PRICE = 'BasePrice'
MODEL_CENTER_PRICE = 'CentersPrices'
MODEL_CENTER = 'ServiceCenters'
MODEL_CONTACT = 'ServiceContacts'
MODEL_REGIONS = 'ServiceRegion'


TYPE_MODEL = (
    (MODEl_PRODUCT, 'тип продукции'),
    (MODEL_CODES, 'код дефекта'),
    (MODEL_PODUCT_MODELS, 'модель продукции'),
    (MODE_BASE_PRICE, 'базовая расценка'),
    (MODEL_CENTER_PRICE, 'индивидуальная расценка'),
    (MODEL_REGIONS, 'регион'),
    (MODEL_CENTER, 'севиснвый центр'),
    (MODEL_CONTACT, 'контакт'),
)

TYPE_ACTION_ON_MODEL = (
    (ACTION_CREATE, 'Создание'),
    (ACTION_UPDATE, 'Изменение'),
    (ACTION_DELETE, 'Удаление'),
)


class ChangeLogs(models.Model):
    changed = models.DateTimeField(auto_now=True, verbose_name=u'Дата/время изменения')
    model = models.CharField(choices=TYPE_MODEL, max_length=255, verbose_name=u'Таблица', null=True)
    record_id = models.IntegerField(verbose_name=u'ID записи', null=True)
    user = models.ForeignKey(User, verbose_name=u'Автор изменения', on_delete=models.CASCADE, null=True)
    action_on_model = models.CharField(choices=TYPE_ACTION_ON_MODEL, max_length=50, verbose_name=u'Действие', null=True)
    data = models.JSONField(verbose_name=u'Изменяемые данные модели', default=dict)
    ipaddress = models.CharField(max_length=15, verbose_name=u'IP адресс', null=True)

    class Meta:
        ordering = ('-changed',)
        verbose_name = 'Действие пользователя'
        verbose_name_plural = 'Действия пользователей'

    def __str__(self):
        return f'{self.id}'

    @classmethod
    def add(cls, instance, user, ipaddress, action_on_model, data, id=None):
        #Создание записи в журнале регистрации изменений
        log = ChangeLogs.objects.get(id=id) if id else ChangeLogs()
        log.model = instance.__class__.__name__
        log.record_id = instance.pk
        if user:
            log.user = user
        log.ipaddress = ipaddress
        log.action_on_model = action_on_model
        log.data = data
        log.save()
        return log.pk

reports/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, Q
from django.urls import reverse
from main.my_validators import ChangeloggableMixin
from servicecentres.models import ServiceCenters
from main.business_logic import REPORT_STATUS, STATUS_DRAFT, WORKTYPE, FACTORIES, MONTH_CHOICES
from products.models import Codes, MainProducts, Models
from django.db.models.signals import pre_save, post_save, pre_delete
from django.dispatch import receiver


def ReportDateValidation(self):
    return Reports.ojects.filter(report_date=self.report_date).exclude(pk=self.pk)


class Reports(ChangeloggableMixin, models.Model):
    service_center = models.ForeignKey(ServiceCenters, on_delete=models.CASCADE, verbose_name='Сервисный центр')
    report_date = models.DateField(verbose_name='Отчетный период')
    note = models.TextField(blank=True, null=True, verbose_name='Примечание')
    invoice = models.CharField(max_length=250, blank=True, null=True, verbose_name='Реквизиты счета')
    act = models.CharField(max_length=250, blank=True, null=True, verbose_name='Реквизиты акта')
    mail_date = models.DateField(blank=True, null=True, verbose_name='Дата приема корреспонденции')
    user = models.ForeignKey(User, verbose_name=u'Автор отчета', on_delete=models.PROTECT, limit_choices_to={'is_staff': False})
    status = models.CharField(choices=REPORT_STATUS, max_length=100, verbose_name='Статус', default=STATUS_DRAFT)
    total_cost = models.FloatField(default=0, verbose_name='Общая сумма по отчету')
    total_work = models.FloatField(default=0, verbose_name='Общая сумма за работы')
    total_part = models.FloatField(default=0, verbose_name='Общая сумма за детали')
    total_move = models.FloatField(default=0, verbose_name='Общая сумма за выезд')
    records_count = models.IntegerField(default=0, verbose_name='Количестов ремонтов')
    verified_count = models.IntegerField(default=0, verbose_name='Количестов принятых ремонтов')
    have_fault = models.BooleanField(default=False, blank=True, verbose_name='Имеет ошибки')
    pay_date = models.DateField(blank=True, null=True, verbose_name='Дата передачи в оплату')

    class Meta():
        verbose_name = 'Отчет'
        verbose_name_plural = 'Отчеты'
        ordering = ['-report_date', 'service_center', 'status']

    def __str__(self):
        date = self.report_date
        return self.service_center.title + ' за ' + date.strftime("%B %Y")

    def get_report_month(self):
        return ' '.join([MONTH_CHOICES[self.report_date.month-1][1], self.report_date.strftime("%Y")])

    def get_absolute_url(self):
        return reverse('report_page', kwargs={"pk": self.pk, })


class ReportsRecords(ChangeloggableMixin, models.Model):
    product = models.ForeignKey(MainProducts, verbose_name='Тип продукции', on_delete=models.PROTECT)
    model = models.ForeignKey(Models, null=True, blank=True, verbose_name='Модель продукции', on_delete=models.PROTECT)
    work_type = models.CharField(choices=WORKTYPE, max_length=50, verbose_name='Вид ремонта')
    client = models.CharField(max_length=150, null=True, blank=True, verbose_name='Клиент')
    client_phone = models.CharField(max_length=150, null=True, blank=True, verbose_name='Телефон клиента')
    client_addr = models.CharField(max_length=250, null=True, blank=True, verbose_name='Адрес клиента')
    model_description = models.CharField(max_length=150, verbose_name='Модель продукции', blank=True)
    serial_number = models.CharField(max_length=30, verbose_name='Серийный номер')
    buy_date = models.DateField(null=True, blank=True, verbose_name='Дата покупки')
    start_date = models.DateField(verbose_name='Дата начала ремонта')
    end_date = models.DateField(verbose_name='Дата окончания ремонта')
    work_cost = models.FloatField(default=0, verbose_name='За работу')
    move_cost = models.FloatField(default=0, verbose_name='За выезд', blank=True)
    problem_description = models.TextField(verbose_name='Описание проблемы')
    work_description = models.TextField(verbose_name='Описание работ', blank=True)
    code = models.ForeignKey(Codes, verbose_name='Код неисправности', on_delete=models.PROTECT, limit_choices_to={'is_folder': False})
    note = models.CharField(max_length=250, verbose_name='Примечание', blank=True)
    report = models.ForeignKey(Reports, verbose_name='Отчет', on_delete=models.CASCADE, blank=True, null=True)
    parts_cost = models.FloatField(default=0, verbose_name='За детали', blank=True)
    total_cost = models.FloatField(default=0, verbose_name='Всего за ремонт', blank=True)

    verified = models.BooleanField(default=False, verbose_name='Принят')
    factory = models.CharField(choices=FACTORIES, null=True, max_length=1, verbose_name='Завод-изготовитель', blank=True)
    main_date = models.DateField(null=True, verbose_name='Дата производства', blank=True)
    shift = models.CharField(null=True, max_length=1, verbose_name='Рабочая смена', blank=True)
    errors = models.TextField(verbose_name='Ошибки', null=True, blank=True)
    remarks = models.TextField(verbose_name='Замечания', null=True, blank=True)
    have_general_errors = models.BooleanField(default=False, verbose_name='Требует внимания старшего менеджера')
    verified_date = models.DateField(verbose_name='Дата приема записи', null=True, blank=True)

    class Meta():
        verbose_name = 'Ремонт'
        verbose_name_plural = 'Ремонты'
        ordering = ['report', ]

    def get_absolute_url(self):
        return reverse('record_update_page', kwargs={"pk": self.pk, })


class ReportsParts(ChangeloggableMixin, models.Model):
    title = models.CharField(max_length=250, verbose_name='Наименование')
    price = models.IntegerField(null=True, blank=True, verbose_name='Цена')
    count = models.IntegerField(null=True, verbose_name='Количество')
    document = models.CharField(max_length=250, verbose_name='Реквизиты накладной')
    record = models.ForeignKey(ReportsRecords, verbose_name='Отчет', on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'Деталь из ремонта'
        verbose_name_plural = 'Детали из ремонта'
        ordering = ['record', 'title']

    def __str__(self):
        return self.title


@receiver(pre_save, sender=Reports)
def report_pre_save(sender, instance, **kwargs):
    qset = instance.reportsrecords_set.all()
    if qset:
        instance.records_count = qset.count()
        result = qset.aggregate(total_sum=Sum('total_cost'))
        instance.total_cost = result['total_sum']
        result = qset.aggregate(parts_sum=Sum('parts_cost'))
        instance.total_part = result['parts_sum']
        result = qset.aggregate(work_sum=Sum('work_cost'))
        instance.total_work = result['work_sum']
        result = qset.aggregate(move_sum=Sum('move_cost'))
        instance.total_move = result['move_sum']
        if qset.filter(~Q(errors=None)):
            instance.have_fault = True
        else:
            instance.have_fault = False
        instance.verified_count = qset.filter(verified=True).count()
        if instance.verified_count == instance.records_count and instance.status == 'received':
            instance.status = 'verified'


@receiver(post_save, sender=ReportsRecords)
def record_post_save(sender, instance, **kwargs):
    instance.report.save()


@receiver(pre_delete, sender=ReportsRecords)
def record_pre_delete(sender, instance, **kwargs):
    instance.product = None
    instance.model = None

main/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import *
from django.contrib import messages
from .my_validators import superuser_validation, staff_validation, StaffUserMixin, user_validation
from .business_logic import datafile_uploaded, datafile_get_format, BASE_PRICE_TYPE
from django.views.generic import View, ListView, TemplateView
from .models import ChangeLogs, TYPE_MODEL
from reports.models import Reports
from servicecentres.models import ServiceCenters
from reports.forms import ReportTitleForm

#начальная страница сайта - авторизация пользователя

class HelpPage(TemplateView):
    template_name = 'main/help_page.html'
    

def site_stop(request):
    return render(request, 'main/site_stop.html')


def start_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if user.is_staff:
                return redirect('staff_home')
            else:
                try:
                    ServiceCenters.objects.get(user=request.user, is_active=True)
                    return redirect('user_home')
                except Exception:
                    messages.error(request, 'Ошибка привязки логина. Продолжение работы не возможно !')
                    return redirect('login_page')
        else:
            messages.error(request, 'Неверное имя пользовтаеля или пароль')
    else:
        form = UserLoginForm()
    return render(request, 'main/index.html', {'form': form})


#домашняя страница рядового пользователя
@user_passes_test(user_validation)
def user_home(request):
    cont = dict()
    reports = Reports.objects.filter(service_center__user=request.user)
    form = ReportTitleForm()
    paginator = Paginator(reports, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    cont['page_obj'] = page_obj
    cont['reports'] = reports
    cont['rep_form'] = form
    return render(request, 'main/user_home.html', cont)


#домашяя страница персоланала
@user_passes_test(staff_validation)
def staff_home(request):
    from .business_logic import STATUS_SEND
    cont = dict()
    logs = ChangeLogs.objects.all()[:3]
    reports = Reports.objects.filter(status=STATUS_SEND)
    if not request.user.groups.filter(name='GeneralStaff').exists() and not request.user.is_superuser:
        reports = reports.filter(service_center__staff_user=request.user)
    cont['staff_actions'] = logs
    cont['reports'] = reports
    return render(request, 'main/staff_home.html', cont)


#выход пользователя
def userlogout(request):
    logout(request)
    return redirect('login_page')


#страница загрузки моделей из файла
@user_passes_test(superuser_validation)
def admin_load_data(request, mod_name):
    cont = {'mod_name': mod_name, 'format_help': datafile_get_format(mod_name)}
    if request.method == 'POST':
        form = DataFileLoadForm(request.POST, request.FILES)
        cont['form'] = form
        if form.is_valid():
            result = datafile_uploaded(request.FILES['file'],mod_name)
            if len(result) != 0:
                msg = 'Ошибки в строках файла: ' +', '.join(result)
                messages.error(request, msg)
            redirect_url = '/admin/' + mod_name.replace('.', '/') + '/'
            return redirect(redirect_url)
    else:
        form = DataFileLoadForm()
        cont['form'] = form
    return render(request, 'main/admin_load_data.html', cont)


#базовый класс для представлений изспользующих формы - позволяет выводить сообщения валидации
class MyFormMessagesView(View):
    success_message = 'my meesage'

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        text=''
        for error in form.errors:
            text = text + form.errors[error]
        messages.error(self.request, text)
        ctx['form'] = form
        return self.render_to_response(ctx)


class LogsList(LoginRequiredMixin, StaffUserMixin, ListView):
    model = ChangeLogs
    template_name = 'main/logs_list.html'
    context_object_name = 'logs'
    extra_context = {'title': 'Изменения данных'}
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = LogsFilterForm(self.request.GET)
        context['obj_count'] = self.object_list.count()
        return (context)

    def get_queryset(self):
        logs = ChangeLogs.objects.all()
        if self.request.GET.get("model", '') != '' and self.request.GET.get("model", '') != 'empty':
            logs = logs.filter(model=self.request.GET.get("model"))
        if self.request.GET.get("action_on_model", '') != '' and self.request.GET.get("action_on_model", '') != 'empty':
            logs = logs.filter(action_on_model=self.request.GET.get("action_on_model"))
        if self.request.GET.get("staff_user", '') != '':
            logs = logs.filter(user=self.request.GET.get("staff_user"))
        return logs

main/templates/main/admin_load_data.html
{% extends 'admin/base_site.html' %}

{% block title %}
    Загрузка данных|Отчеты RENOVA
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <style type="text/css">
       #centerLayer {
        margin-left: 20%; /* Отступ слева */
        width: 60%; /* Ширина слоя */
        padding: 10px; /* Поля вокруг текста */
       }
    </style>
{% endblock %}

{% comment %}{% block breadcrumbs %}
{% endblock %}{% endcomment %}

{% block content %}
    <div id="centerLayer">
        <h1>Загрузка модели из текстового файла</h1>
        <form action="" method="post" id="save_form" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Модель: {{ mod_name }}</h2>
            Требуемый формат файла: {{ format_help }} (UTF-8)
            <h2>Загружаемые данные:</h2>
            {{ form.file }}
            <p>{{ form.file.errors }}</p>
            <input type="submit" value="Записать в базу данных" class="default align-right">
        </form>
   </div>
{% endblock %}

main/templates/main/site_stop.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}


{% block title %}
    {{ block.super }}|Сайт недоступен
{% endblock %}

{% block content %}
<nav class="navbar sticky-top navbar-expand-md navbar-light bg-light" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><strong>RENOVA</strong></a>
    </div>
</nav>

<div class="container py-5 text-center">
    <h1>ИЗВИНИТЕ</h1>
    <H2>САЙТ ВРЕМЕННО НЕДОСТУПЕН !</H2>
</div>

{% include 'inc/footer.html' %}
{% endblock %}

main/templates/main/tag_log_data.html
<div class="card mb-3">
    <div class="card-body">
        <div class="row py-1 bg-light text-dark border border-border">
            <strong>{{ action.get_model_display|capfirst }} - {{ action.get_action_on_model_display|lower }} </strong>
        </div>
        <div class="col-12 mt-1">
            {% for line in obj_description %}
            {{ line }}<br>
            {% endfor %}
        </div>
        <div class="row mt-1">
            {% for key,val in data.items %}
            <div class="row">
                <div class="col-auto"><strong>{{ key }}:</strong></div>
                <div class="col-auto">{{ val }}</div>
            </div>
            {% endfor %}
        </div>
        <div class="row mt-2">
            <div class="col-sm-4">
                <h6 class="card-title text-muted">{{ action.user }}</h6>
            </div>
            <div class="col-auto">
                <h6 class="card-title text-muted">{{ action.changed }}</h6>
            </div>
        </div>
    </div>
 </div>

main/templates/main/tag_parts_list.html
<div class="row g-1">
    {% for part in parts %}
    <label class="col-xl-8">{{ part.title|truncatewords:5 }}</label>
    {% if part.price and part.price != 0 %}
    <label class="col-xl-4">{{ part.count }} X {{ part.price }}</label>
    {% else %}
    <label class="col-xl-4">{{ part.count }} шт</label>
    {% endif %}
    {% endfor %}
</div>

main/templates/main/tag_products_list.html
<div class="col-lg-3">
    <div class="list-group">
        {% for product in products %}
        <a class="list-group-item list-group-item-action" href="#Item-{{ forloop.counter }}">
            {{ product.short_title }}
        </a>
        {% endfor %}
    </div>
</div>

main/templates/main/tag_records_form_fields_errors.html
<span class="badge rounded-pill bg-danger"
      data-bs-toggle="tooltip" data-bs-html="true"
      title="{{ errors }}">
    !
</span>

main/templates/main/tag_report_header.html
<div class="card text-dark bg-light" >
    <div class="card-body ">
        <div class="row">
            <div class="col-md-4 col-lg-3">
                <h5>{{ report.report_date|date:"F Y" }}</h5>
            </div>
            <div class="col-md-3">
                {% if report.status == 'draft' %}
                <h5 class="text-muted">{{ report.get_status_display }}</h5>
                {% elif report.status == 'refinement' %}
                <h5 class="text-danger">{{ report.get_status_display }}</h5>
                {% elif report.status == 'send' or report.status == 'received' %}
                <h5 class="text-warning">{{ report.get_status_display }}</h5>
                {% elif report.status == 'verified' or report.status == 'accepted' %}
                <h5 class="text-info">{{ report.get_status_display }}</h5>
                {% else %}
                <h5 class="text-success">{{ report.get_status_display }}</h5>
                {% endif %}
            </div>
            <div class="col text-end position-absolute top-1 end-0">
                {% if can_edit %}
                    {% if report.status == 'draft' or report.status == 'refinement' %}
                    <button type="button" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#addModal_{{ report.pk }}">
                        <i class="bi bi-pencil"></i>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="addModal_{{ report.pk }}" tabindex="-1" aria-labelledby="addModalLabel_{{ report.pk }}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="addModalLabel_{{ report.pk }}">Изменить заголовок отчета</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form method="POST" action="{% url 'report-update' report.pk %}">
                                    {% csrf_token %}
                                    <div class="modal-body">
                                        <div class="row g-2 text-start">
                                            <div class="col-xl-4">Отчетный период:</div>
                                            <div class="col-md-5">{{ rep_form.month }}</div>
                                            <div class="col-md-3">{{ rep_form.year }}</div>
                                            <div class="col-xl-4">Примечание:</div>
                                            <div class="col-md-8">{{ rep_form.note }}</div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary btn-sm">Изменить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% else %}
                <a href="{% url 'report_page' report.pk %}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-eye"></i></i></a>
                {% endif %}
                {% if report.records_count > 0 %}
                    {% if report.status == 'draft' or report.status == 'refinement' %}
                    <button type="button" class="btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#sendModal_{{ report.pk }}">
                        <i class="bi bi-send-fill"></i>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="sendModal_{{ report.pk }}" tabindex="-1" aria-labelledby="addModalLabel_{{ report.pk }}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="sendModalLabel_{{ report.pk }}">Отправить отчет на проверку ?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="card-body text-start">
                                    <p>Отчет за {{ report.report_date|date:"F Y"|lower }}</p>
                                    <div class="collapse" id="collapseExample">
                                        <p class="fs-6 text-black-50">Ваш менеджер будет автоматически уведомлен по электронной почте. Отправка сообщения может занять некоторое время ..</p>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <form method="POST" action="{% url 'report-send' %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary btn-sm" name="send"
                                                value="{{ report.pk }}" data-bs-toggle="collapse" data-bs-target=
                                                        "#collapseExample" aria-expanded="false" aria-controls=
                                                        "collapseExample">
                                            Отправить
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    <a href="{% url 'report_export' report.pk %}" class="btn btn-outline-secondary btn-sm btn-sm">
                        <i class="bi bi-save"></i>
                    </a>
                {% endif %}
                {% if report.status == 'draft' %}
                <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#delete_{{ report.pk }}">
                    <i class="bi bi-trash"></i>
                </button>
                <!-- Modal -->
                <div class="modal fade" id="delete_{{ report.pk }}" tabindex="-1" aria-labelledby="deleteLabel_{{ report.pk }}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteLabel_{{ report.pk }}">Удалить черновик отчета ?</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="card-body text-start">Отчет за {{ report.report_date|date:"F Y"|lower }}</div>
                            <div class="modal-footer">
                                <a href="{% url 'report_delete' report.pk %}" class="btn btn-danger btn-sm" tabindex="-1" role="button" aria-disabled="true">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-lg-2">Ремонты: {{ report.records_count }}</div>
            <div class="col-lg-3">За работы: {{ report.total_work }} руб</div>
            <div class="col-lg-3">За детали: {{ report.total_part }} руб</div>
            <div class="col-lg-3">За выезд: {{ report.total_move }} руб</div>
            <h6 class="col-12">Всего по отчету: {{ report.total_cost }} руб</h6>
        </div>
        <div class="row mt-3 justify-content-between">
            <div class="col-10">
                {% if report.note %}
                <i class="bi bi-info-square"></i><label class="px-3">{{ report.note }}</label>
                {% endif %}
            </div>
            {% if can_edit and report.status == 'draft' %}
            <div class="col-2 text-end">
                <a href="{% url 'record_add_page' report.pk %}" class="btn btn-outline-primary btn-sm btn-sm">Добавить запись</a>
            </div>
            {% endif %}
        </div>
        {% if report.have_fault %}
        <div class="row mt-2">
            <div class="col-12">
                <i class="bi bi-exclamation-square-fill text-warning"></i><strong class="px-3">есть записи с ошибками !</strong>
            </div>
        </div>
        {% endif %}
    </div>
</div>

main/templates/main/tag_show_base_price_links.html
{% for item,value in base_price_type %}
<li><a class="dropdown-item" href="{% url 'prices_list_page' item %}">Расценки по прайсу "{{ value }}"</a></li>
{% endfor %}