main/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', start_login, name='login_page'),
    #path('', site_stop),
    path('user_home/', user_home, name='user_home'),
    path('logout/', userlogout, name='user_logout'),
    path('staff_home/', staff_home, name='staff_home'),
    path('load_data/<str:mod_name>/', admin_load_data, name='admin_load_data_page'),
    path('logs_list/', LogsList.as_view(), name='logs_page'),
    path('help/', HelpPage.as_view(), name='help_page'),
]

products/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('list/', ProductsList.as_view(), name='products_list_page'),
    path('code_and_prices-list', CodeAndPriceList.as_view(), name='code_and_prices_page'),
    path('code_and_prices-list/<int:center_pk>', CodeAndPriceList.as_view(), name='code_and_prices_page'),
    path('code-add/', CodesAdd.as_view(), name='code_add_page'),
    path('code-update/<int:pk>', CodesUpdate.as_view(), name='code_update_page'),

    path('price-add/', BasePriceAdd.as_view(), name='price_add_page'),
    path('price-add/<int:code_pk>', BasePriceAdd.as_view(), name='price_add_page'),
    path('price-add/<str:price_type>', BasePriceAdd.as_view(), name='price_add_page'),
    path('prices-list/<str:price_type>', BasePriceList.as_view(), name='prices_list_page'),
    path('price-update/<int:pk>', BasePriceUpdate.as_view(), name='price_update_page'),
    path('price-delete/<int:price_pk>', BasePriceDelete, name='price_delete_page'),

    path('centerprices-list/<int:code_pk>', CodePricesPage.as_view(), name='code_prices_page'),
    path('centerprice-add/', CenterPriceAdd.as_view(), name='centerprice_add_page'),
    path('centerprice-add/<int:code_pk>', CenterPriceAdd.as_view(), name='centerprice_add_page'),
    path('centerprice-add/<int:code_pk>/<int:center_pk>', CenterPriceAdd.as_view(), name='centerprice_add_page'),
    path('centerprice-update/<int:pk>', CenterPriceUpdate.as_view(), name='centerprice_update_page'),
    path('ajax/price-load-groups/', load_groups, name='ajax_load_groups'),
    path('centerprice-delete/<int:price_pk>', CenterPriceDelete, name='centerprice_delete_page'),

    #path('products-loading/', ProductsLoading, name='products_loading_page'),
    path('products-loading/', UploadProductionFiles, name='products_loading_page'),
    path('productions-list/', ProductionsList.as_view(), name='productions_list_page'),
    path('products-move/', MoveProductionFiles, name='products_move_page'),

]

reportssite/urls.py
from functools import partial
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import server_error, page_not_found, permission_denied


handler403 = partial(permission_denied, template_name='errs/403.html')
handler404 = partial(page_not_found, template_name='errs/404.html')
handler500 = partial(server_error, template_name='errs/500.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('centres/', include('servicecentres.urls')),
    path('products/', include('products.urls')),
    path('reports/', include('reports.urls')),
    path('import/', include('importData.urls'))
]

products/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.urls import reverse
from servicecentres.models import ServiceCenters
from main.my_validators import ChangeloggableMixin
from main.signals import journal_save_handler, journal_delete_handler
from main.business_logic import *

REPAIR_CHOICES = [
    ('none', 'не указывается'),
    ('document', 'выписка документов'),
    ('easy', 'простой'),
    ('middle', 'средний'),
    ('difficult', 'сложный'),
    ('very_difficult', 'очень сложный'),
    ('type1', 'специальный 1'),
    ('type2', 'специальный 2'),
    ('type3', 'специальный 3'),
    ('type4', 'специальный 4'),
    ('type5', 'специальный 5'),
    ('type6', 'специальный 6'),
    ('type7', 'специальный 7'),
    ('type8', 'специальный 8'),
    ('type9', 'специальный 9'),
    ('type10', 'специальный 10'),
]


class MainProducts(ChangeloggableMixin, models.Model):
    title = models.CharField(max_length=50, unique=True, verbose_name='Наименование')
    short_title = models.CharField(max_length=20, null=True, blank=True, unique=True, verbose_name='Краткое наименование')
    valid_date = models.DateField(null=True, blank=True, verbose_name='Дата начала проверки производства')
    guarantee_period = models.IntegerField(default=1, verbose_name='Гарантийный срок')
    check_serial = models.BooleanField(default=False, blank=True, verbose_name='Проверять серийный номер')

    class Meta():
        verbose_name = 'Вид продуктции'
        verbose_name_plural = 'Виды продуктции'
        ordering = ['title']

    def __str__(self):
        return self.title


class Models(ChangeloggableMixin, models.Model):
    title = models.CharField(max_length=50, unique=True, verbose_name='Наименование')
    code_chars = models.CharField(max_length=10, null=True, blank=True, verbose_name='Буквенная кодировка')
    west_id = models.IntegerField(null=True, blank=True, verbose_name='Цифровая кодировка Запад')
    east_id = models.IntegerField(null=True, blank=True, verbose_name='Цифровая кодировка Восток')
    product = models.ForeignKey(MainProducts, null=True, related_name='parent_product', on_delete=models.PROTECT, verbose_name='Вид продукции')

    class Meta():
        verbose_name = 'Модель продукции'
        verbose_name_plural = 'Модели продукции'
        ordering = ['product', 'title']

    def __str__(self):
        return self.title


class Codes(ChangeloggableMixin, models.Model):
    product = models.ForeignKey(MainProducts, null=True, blank=True, related_name='code_product', on_delete=models.CASCADE, verbose_name='Вид продукции')
    parent = models.ForeignKey('self', limit_choices_to={'is_folder': True}, blank=True, null=True, related_name='parent_code', on_delete=models.CASCADE, verbose_name='Группа дефектов')
    is_folder = models.BooleanField(blank=True, verbose_name='Это группа')
    code = models.CharField(max_length=5, verbose_name='Код ошибки')
    title = models.CharField(max_length=150, verbose_name='Описание ошибки')
    repair_type = models.CharField(max_length=50, choices=REPAIR_CHOICES, verbose_name='Вид ремонта')
    is_active = models.BooleanField(default=True, verbose_name='Используется')

    class Meta():
        verbose_name = 'Код неисправиности'
        verbose_name_plural = 'Коды неисправностей'
        ordering = ['product', 'code']

    def __str__(self):
        return self.code + ' ' + self.title

    def clean(self):
        ABC = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        #parent
        if self.is_folder and self.parent:
            raise ValidationError('Для группы родителькая группа не указывается!')
        if not self.is_folder and not self.parent:
            raise ValidationError('Укажите родительскую группу!')
        if self.parent and self.product and self.product != self.__class__.objects.get(pk=self.parent_id).product:
            raise ValidationError('Группа кодов не принадлежит выбранной продукции!')
        #code
        if self.is_folder:
            if len(self.code) > 1:
                raise ValidationError('Для группы длина кода должна бвть не более одного символа!')
            if self.code not in ABC:
                raise ValidationError('Код должен быть заглавной буквой латинского алфавита!')
        else:
            if self.product:
                if self.code[0] not in ABC:
                    raise ValidationError('Код должен начинаиться с заглавной буквы латинского алфавита!')
                if len(self.code) <= 1:
                    raise ValidationError('Код элемента должен быть длинее одного символа!')
                elif not self.code[1:].isdigit():
                    raise ValidationError('Неверный формат кода! Например: "А123"!')
            else:
                if len(self.code) > 1:
                    raise ValidationError('Для для общих кодов длина должна бвть не более одного символа!')
                if not self.code.isdigit():
                    raise ValidationError('Общие коды состоят только из цифр !')
        #тип ремонта
        if self.is_folder:
            if self.repair_type != 'none':
                raise ValidationError('Для группы кодов тип ремонта не указывается!')
        #Уникальность записи
        if self.is_active and self.__class__.objects.filter(product=self.product, code=self.code).exclude(pk=self.pk):
            raise ValidationError('Для этой продукции уже существует такой же активный код!')

    def get_absolute_url(self):
        return reverse('code_update_page', kwargs={"pk": self.pk})


class BasePrice(ChangeloggableMixin, models.Model):
    product = models.ForeignKey(MainProducts, null=True, blank=True, on_delete=models.CASCADE, verbose_name='Вид продукции')
    price_type = models.CharField(choices=BASE_PRICE_TYPE, max_length=100, verbose_name='Тип прайса', default=PRICE_LITE)
    repair_type = models.CharField(max_length=50, choices=REPAIR_CHOICES, verbose_name='Вид ремонта')
    price = models.IntegerField(default=0, verbose_name='Расценка', validators=[MinValueValidator(limit_value=1,
                                message='Расценка должна быть больше чем ноль !'), ])

    class Meta():
        verbose_name = 'Базовая расценка>'
        verbose_name_plural = 'Базовые расценки'
        ordering = ['product', 'price_type', 'repair_type']

    def __str__(self):
        if self.product and self.product.title:
            return self.product.title + ' ' + self.get_price_type_display + ' ' + self.get_repair_type_display + ' ' + str(self.price)
        else:
            return 'Для всей прдукции ' + ' ' + self.get_price_type_display + ' ' + self.get_repair_type_display + ' ' + str(self.price)

    def get_absolute_url(self):
        return reverse('price_update_page', kwargs={"pk": self.pk})


class CentersPrices(ChangeloggableMixin, models.Model):
    service_center = models.ForeignKey(ServiceCenters, on_delete=models.CASCADE, verbose_name='Сервисный центр')
    product = models.ForeignKey(MainProducts, null=True, blank=True, on_delete=models.CASCADE, verbose_name='Вид продукции')
    group = models.ForeignKey(Codes, related_name="price_parent_group", on_delete=models.CASCADE, verbose_name='Группа дефектов')
    code = models.ForeignKey(Codes, on_delete=models.CASCADE, verbose_name='Код неисправности')
    price = models.IntegerField(default=0, verbose_name='Расценка', validators=[MinValueValidator(limit_value=1,
                                message='Расценка должна быть больше чем ноль !'), ])

    class Meta():
        verbose_name = 'Индивидуальная расценка>'
        verbose_name_plural = 'Индивидуальные расценки'
        ordering = ['service_center', 'product', 'group', 'code']

    def __str__(self):
        return self.service_center.title + ' ' + self.code.code + ' ' + self.code.title + ' ' + str(self.price)

    def get_absolute_url(self):
        return reverse('center_price_page', kwargs={"pk": self.pk, })


class Production(models.Model):
    date = models.DateTimeField(verbose_name='Дата и время производства')
    type_pk = models.IntegerField(default=0, verbose_name='PK типа продукции')
    code = models.CharField(max_length=50, unique=False, verbose_name='Код')
    shop = models.CharField(max_length=255, verbose_name='Производственное подразделение')

    class Meta():
        verbose_name = 'Запись о производстве'
        verbose_name_plural = 'Записи о производстве'
        ordering = ['date', ]

    def __str__(self):
        return f'Дата: {self.date}; ' +\
               f'ID продукции: {self.type_pk}; ' +\
               f'Код: {self.code}; ' +\
               f'Производитель: {self.shop}'


# подключение сигналов для записи измеений
# взято отсюда: https://webdevblog.ru/logirovanie-izmeneniya-dannyh-v-modelyah-django/

post_save.connect(journal_save_handler, sender=Codes)
post_delete.connect(journal_delete_handler, sender=Codes)
post_save.connect(journal_save_handler, sender=BasePrice)
post_delete.connect(journal_delete_handler, sender=BasePrice)
post_save.connect(journal_save_handler, sender=CentersPrices)
post_delete.connect(journal_delete_handler, sender=CentersPrices)
post_save.connect(journal_save_handler, sender=Models)
post_delete.connect(journal_delete_handler, sender=Models)
post_save.connect(journal_save_handler, sender=MainProducts)
post_delete.connect(journal_delete_handler, sender=MainProducts)

products/templates/product/baseprice_add.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
{% include 'inc/staff_navbar.html' %}

<div class="container col-lg-5">
    <div class="row py-4 col-12">
        <h3>{{ title }}</h3>
    </div>
    <form class="row py-5 g-3" method="post">
        {% csrf_token %}
        <div class="row mb-3">
            <label class="col-sm-4 col-form-label">Тип прайса</label>
            <div class="col-sm-8"> {{ form.price_type }} </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-4 col-form-label">Тип продукции</label>
            <div class="col-sm-8"> {{ form.product }} </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-4 col-form-label">Тип ремонта</label>
            <div class="col-sm-8"> {{ form.repair_type }} </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-4 col-form-label">Расценка</label>
            <div class="col-sm-3"> {{ form.price }}  </div>
            <label class="col-sm-5 col-form-label">руб</label>
        </div>
        <div class="row mt-5 justify-content-between">
            <div class="col-lg-1">
                {% if form.instance and form.instance.pk %}
                {% if request.user|has_group:'GeneralStaff' or request.user.is_superuser %}
                <a class="btn btn-outline-danger" href="{% url 'price_delete_page' form.instance.pk %}?next={{next}}" role="button">Удалить</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="col-lg-11 text-end">
                {% if form.instance and form.instance.pk %}
                <button type="submit" class="btn btn-primary" name="close">Записать и закрыть</button>
                {% else %}
                <button type="submit" class="btn btn-outline-secondary" name="close">Записать и закрыть</button>
                <button type="submit" class="btn btn-primary" name="save">Записать и добавить еще</button>
                {% endif %}
            </div>
        </div>
    </form>
</div>


{% include 'inc/footer.html' %}
{% endblock %}

products/templates/product/baseprices_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% if request.user.is_staff %}
{% include 'inc/staff_navbar.html' %}
{% endif %}

<div class="container">
    <main>
        <div class="row py-4 justify-content-between">
            <div class="col-11"><h3>{{ title }}</h3></div>
            <div class="col-1">
                {% if request.user|has_group:'GeneralStaff' or request.user.is_superuser  %}
                <a class="btn btn-primary" href="{% url 'price_add_page' price_type %}?next={{ request.path }}" role="button">Добавить</a>
                {% endif %}
            </div>
        </div>
        {% if prices %}
        <div class="row g-5">
            <!-- список продуктов --!>
            {% show_products_list products %}
            <!-- вывод цен --!>
            <div class="col-lg-9">
                <!-- общие расценки --!>
                <div class="container mb-3" id="Item-0">
                    <diw class="row bg-light justify-content-between">
                        <div class="col-auto">
                            <h5>Общие коды</h5>
                        </div>
                        <div class="col-auto">
                            <a data-bs-toggle="collapse" href="#collapse-0" aria-expanded="false" aria-controls="collapseExample">
                                <i class="bi bi-arrow-down-up"></i>
                            </a>
                        </div>
                    </diw>
                    <div class="row collapse show" id="collapse-0">
                        <hr>
                        {% for price in general_prices %}
                        <div class="row col-10 px-5 bg-white">
                            <div class="col-sm-6">
                                {% if request.user|has_group:'GeneralStaff' or request.user.is_superuser  %}
                                <a href="{{ price.get_absolute_url }}?next={{ request.path }}" style="text-decoration: none">{{ price.get_repair_type_display }}</a>
                                {% else %}
                                {{ price.get_repair_type_display }}
                                {% endif %}
                            </div>
                            <div class="col-sm-1">
                                {{ price.price }}
                            </div>
                            <div class="col-sm-1">
                                руб
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- расценки по типам продукции --!>
                {% for product in products %}
                <div class="container mb-3" id="Item-{{ forloop.counter }}">
                    <diw class="row bg-light justify-content-between">
                        <div class="col-auto">
                            <h5>{{ product.title }}</h5>
                        </div>
                        <div class="col-auto">
                            <a data-bs-toggle="collapse" href="#collapse-{{ forloop.counter }}" aria-expanded="False" aria-controls="collapseExample".>
                                <i class="bi bi-arrow-down-up"></i>
                            </a>
                        </div>
                    </diw>

                    <div class="row collapse show" id="collapse-{{ forloop.counter }}">
                        <hr>
                        {% for price in prices %}
                        <div class="row col-10 px-5 bg-white">
                            {% if price.product == product %}
                            <div class="col-sm-6">
                                {% if request.user|has_group:'GeneralStaff' or request.user.is_superuser %}
                                <a href="{{ price.get_absolute_url }}?next={{ request.path }}" style="text-decoration: none">{{ price.get_repair_type_display }}</a>
                                {% else %}
                                {{ price.get_repair_type_display }}
                                {% endif %}
                            </div>
                            <div class="col-sm-1">
                                {{ price.price }}
                            </div>
                            <div class="col-sm-1">
                                руб
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- кнопка ВВЕРХ --!>
        {% include 'inc/go_to_top_button.html' %}
        {% else %}
        <h4 class="text-center text-muted">Ничего не найдено ...</h4>
        {% endif %}
    </main>
    {% include 'inc/list_paginator.html' %}
</div>

{% include 'inc/footer.html' %}
{% endblock %}

products/templates/product/center_price_add.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
{% include 'inc/staff_navbar.html' %}

<div class="container col-lg-7">
    <div class="row py-4 col-12">
        <h3>{{ title }}</h3>
    </div>
    <div class="container col-lg-12">
        <form class="row  g-3" method="post" id="priceForm" data-group-url="{% url 'ajax_load_groups' %}" novalidate>
        {% csrf_token %}
            <div class="col-lg-12">
                <label class="col-sm-4 col-form-label">Сервисный центр
                    {% if form.service_center.errors %}
                    {% show_record_form_field_errors form.service_center.errors %}
                    {% endif %}
                </label>
                {{ form.service_center }}
            </div>
            <div class="col-lg-6">
                <label class="col-sm-4 col-form-label">Продукция
                    {% if form.product.errors %}
                    {% show_record_form_field_errors form.product.errors %}
                    {% endif %}
                </label>
                {{ form.product }}
            </div>
            <div class="col-lg-6">
                <label class="col-sm-4 col-form-label">Группа кодов
                    {% if form.group.errors %}
                    {% show_record_form_field_errors form.group.errors %}
                    {% endif %}
                </label>
                {{ form.group }}
            </div>
            <div class="col-lg-12">
                <label class="col-sm-4 col-form-label">Код
                    {% if form.code.errors %}
                    {% show_record_form_field_errors form.code.errors %}
                    {% endif %}
                </label>
                {{ form.code }}
            </div>
            <div class="col-lg-3">
                <label class="col-sm-4 col-form-label">Расценка
                    {% if form.price.errors %}
                    {% show_record_form_field_errors form.price.errors %}
                    {% endif %}
                </label>
                {{ form.price }}
            </div>
        <div class="row mt-5 justify-content-between">
            <div class="col-lg-1">
                {% if form.instance and form.instance.pk %}
                {% if request.user|has_group:'GeneralStaff' or request.user.is_superuser %}
                <a class="btn btn-outline-danger" href="{% url 'centerprice_delete_page' form.instance.pk %}?next={{next}}" role="button">Удалить</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="col-lg-11 text-end">
                {% if form.instance and form.instance.pk %}
                <button type="submit" class="btn btn-primary" name="close">Записать и закрыть</button>
                {% else %}
                <button type="submit" class="btn btn-outline-secondary" name="close">Записать и закрыть</button>
                <button type="submit" class="btn btn-primary" name="save">Записать и добавить еще</button>
                {% endif %}
            </div>
        </div>
    </form>
    </div>
</div>

{% include 'inc/footer.html' %}

<!-- AJAX скрип для динамического изменения списков без перезагрузки страницы --!>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_product").change(function () {
      var url = $("#priceForm").attr("data-group-url");
      var productId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'product': productId
        },
        success: function (data) {
          $("#id_group").html(data);
          $("#id_code").html('<option value="">---------</option>');
        }
      });
    });

    $("#id_group").change(function () {
      var url = $("#priceForm").attr("data-group-url");
      var groupId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'group': groupId
        },
        success: function (data) {
          $("#id_code").html(data);
        }
      });
    });
 </script>

{% endblock %}

products/templates/product/code_add.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
{% include 'inc/staff_navbar.html' %}

<div class="container col-8">
    <div class="row py-4 col-6">
        <h3>{{ title }}</h3>
    </div>
    <form class="row g-3" method="post" id="codeForm" data-group-url="{% url 'ajax_load_groups' %}" novalidate>
        {% csrf_token %}
        <div class="col-lg-6">
            <label class="form-label">Вид продукции</label>
            {{ form.product }}
        </div>
        <div class="col-lg-6">
            <label class="form-label">Родительская группа</label>
            {{ form.parent }}
        </div>
        <div class="col-lg-12 mt-4">
            <div class="form-check">
                {{ form.is_folder }}
                <label class="form-label">- это группа</label>
            </div>
        </div>
        <div class="col-lg-1">
            <label class="form-label">Код</label>
            {{ form.code }}
        </div>
        <div class="col-lg-9">
            <label class="form-label">Описание кода</label>
            {{ form.title }}
        </div>
        <div class="col-lg-2">
            <label class="form-label">Вид ремонта</label>
            {{ form.repair_type }}
        </div>
        <div class="col-lg-12 mt-4">
            <div class="form-check">
                {{ form.is_active }}
                <label class="form-label">- активен</label>
            </div>
        </div>
        <div class="col-lg-12 text-end">
            {% if form.instance and form.instance.pk %}
            <button type="submit" class="btn btn-primary" name="close">Записать и закрыть</button>
            {% else %}
            <button type="submit" class="btn btn-outline-secondary" name="close">Записать и закрыть</button>
            <button type="submit" class="btn btn-primary" name="save">Записать и добавить еще</button>
            {% endif %}
        </div>
    </form>
</div>


{% include 'inc/footer.html' %}

<!-- AJAX скрип для динамического изменения списков без перезагрузки страницы --!>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_product").change(function () {
      var url = $("#codeForm").attr("data-group-url");
      var productId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'product': productId
        },
        success: function (data) {
          $("#id_parent").html(data);
        }
      });
    });
 </script>

{% endblock %}

products/templates/product/codes_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% if request.user.is_staff %}
{% include 'inc/staff_navbar.html' %}
{% else %}
{% include 'inc/user_navbar.html' %}
{% endif %}

<div class="container">
    <main>
        <div class="row py-4 justify-content-between">
            <div class="col-7">
                <h3>{{ title }}<label class="text-muted">{{ center.title }}</label></h3>
            </div>
            <div class="col-5 text-end">
                {% if request.user.is_superuser or request.user|has_group:'GeneralStaff' %}
                    {% if center %}
                    <a class="btn btn-primary" href="{% url 'centerprice_add_page' 0 center.pk %}" role="button">
                        Добавить индивидуальную расценку
                    </a>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'centerprice_add_page'%}" role="button">
                        Добавить индивидуальную расценку
                    </a>
                    <a class="btn btn-primary" href="{% url 'code_add_page' %}" role="button">
                        Добавить код
                    </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <div class="row g-5">
            <!-- список продуктов --!>
            {% show_products_list products %}
            <!-- вывод кодов --!>
            <div class="col-lg-9">
                <!-- общие коды --!>
               <div class="container mb-3" id="Item-0">
                    <diw class="row bg-light justify-content-between">
                        <div class="col-auto">
                            <h5>Общие коды</h5>
                        </div>
                        <div class="col-auto">
                            <a data-bs-toggle="collapse" href="#collapse-0" aria-expanded="false" aria-controls="collapseExample">
                                <i class="bi bi-arrow-down-up"></i>
                            </a>
                        </div>
                    </diw>
                    <div class="row collapse show" id="collapse-0">
                        <hr>
                        {% show_code_for_product request.user None center %}
                    </div>
                </div>
                <!-- по типам продукции -->
                {% for product in products %}
                <div class="container mb-3" id="Item-{{ forloop.counter }}">
                    <diw class="row bg-light justify-content-between">
                        <div class="col-auto">
                            <h5>{{ product.title }}</h5>
                        </div>
                        <div class="col-auto">
                            <a data-bs-toggle="collapse" href="#collapse-{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseExample">
                                <i class="bi bi-arrow-down-up"></i>
                            </a>
                        </div>
                    </diw>
                    <div class="row collapse show" id="collapse-{{ forloop.counter }}">
                        <hr>
                        {% show_code_for_product request.user  product center %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- кнопка ВВЕРХ --!>
        {% include 'inc/go_to_top_button.html' %}
    </main>
    {% include 'inc/list_paginator.html' %}
</div>

{% include 'inc/footer.html' %}
{% endblock %}

products/templates/product/codes_list_pause.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% if request.user.is_staff %}
{% include 'inc/staff_navbar.html' %}
{% else %}
{% include 'inc/user_navbar.html' %}
{% endif %}

<div class="container col-lg-5">

    <form class="row py-5" method="post">
        {% csrf_token %}
        <div class="col-lg-12 py-5  text-center">
        <h3 class="text-muted">ПОДГОТАВЛИВАЕМ ДАННЫЕ, ПОЖАЛУЙСТА ЖДИТЕ</h3>
        </div>
        <div class="text-center">
            <div class="spinner-border text-primary" role="status">
                <span class="visually-hidden">Загрузка...</span>
            </div>
        </div>
        <input type="submit" id="btn1" onclick="clickButton()" style="display:none;" name="butt_1" value="Show Stats">
    </form>

    <!---
    скрипт нажимает на невидимую кнопуку через время задержки
    за это время основная страница должна загрузится
    ---!>
    <script type="text/javascript">

    // Simulate click function
    function clickButton() {
        document.querySelector('#btn1').click();
    }
    // Timeout
    setTimeout(clickButton, 1000);
</script>

</div>

{% endblock %}

products/templates/product/grouplist_get.html
<option value="">---------</option>
{% for group in groups %}
<option value="{{ group.pk }}">{{ group }}</option>
{% endfor %}